version: '2'
networks:
  default:
    external:
      name: testwifi
services:
    mysql1:
      container_name: "mysql1"
      image: mysql:5.7
      volumes:
          - ./${MYSQL1_SAVE_PATH}:/var/lib/mysql

      ports:
          - "3306:3306"
      environment:
          - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
          - MYSQL_DATABASE=${DATABASE}
      restart: always
    
    mysql2:
      container_name: "mysql2"
      image: mysql:5.7
      volumes:
          - ./${MYSQL2_SAVE_PATH}:/var/lib/mysql

      ports:
          - "8081:3306"
      environment:
          - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
          - MYSQL_DATABASE=${DATABASE}
      restart: always
    
    kingshard:
      container_name: "kingshard"
      image: mysql:5.7
      image: matjazmav/kingshard
      volumes:
          - ./ks1.yaml:/etc/ks.yaml
      ports:
          - "9090:9090"

      environment:
          - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
          - MYSQL_DATABASE=${DATABASE}
      links:
          - mysql1
          - mysql2
      restart: always
#networks: # docker网络设置
#  mysql: # 自定义网络名称
#    driver: bridge # 桥接
#    ipam: # 要使用静态ip必须使用ipam插件
#      driver: default
#      config:
#      - subnet: 172.17.0.0/16
#        gateway: 172.17.0.1